### ISSUE TITLE
Support for uploading binary files

### ISSUE THREAD

**Issue by kjellwinblad** [emqx/emqx-dashboard-web#377]
I have added a field of type file to the Kafka resource settings (see screenshot). Unfortunately, the uploaded file's content gets corrupted before it is received at the Erlang backend. I see this because the the number of bytes in the Erlang binary representing the file content is different from the number of bytes in the uploaded file. I'm also attaching [bin_files.zip](https://github.com/emqx/emqx-dashboard-web/files/9012375/bin_files.zip) which contains an example of a binary file that gets corrupted and how it looks like after corruption so that you have something to experiment with (they are placed in a zip file because github does not allow uploads of files with arbitrary extensions).

So what is need is a way to upload binary files using the resource editor UI without getting the files corrupted. We need this for the Kafka Kerberos authentication support that will be added in emqx-enterprise 4.4 and 5.0. So I think a fix for this needs to be added to the branches `dev/4.4` and `dev/5.0.0`.

Please let me know if you have any questions regarding this.

![screenshot](https://user-images.githubusercontent.com/200374/176487299-b2ea45fa-4cdd-48d7-8fe8-7706852d1651.png)

**Comment by Kinplemelon** [comment]
JavaScript can't judge whether the file content is binary or normal text(I'm not totally confirmed), so if you want to upload a binary file, maybe you can add a field type called `binary`, so that if I recognize a field is a binary type, I will allow user upload file and read the file as binary; in this way, you should confirm every user will upload a binary file in this field, this is important, please have a check. another question is dashboard can't pass binary to backend by JSON format, so I will encode data to base64.
if you think this solution is feasible, leave a comment please. or another solution you think is better
@kjellwinblad

**Comment by kjellwinblad** [comment]
@Kinplemelon I think the new field solution that you suggested sounds like a good solution. We can call this new field type `binary` as you suggest or `binary_file` if you think that is more clear. The naming is up to you to decide. It is okey that the backed receive base64 encoded data.

**Comment by Kinplemelon** [comment]
I mock some data for test and it looks good, you can test by using dev/4.4 branch.

https://user-images.githubusercontent.com/26165221/177089865-69c833d0-8442-456d-945e-11fbc104cc57.mov

**Comment by Kinplemelon** [comment]
I will close this issue
